name = "paranoia"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dev-dependencies]
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
M_time    = { git = "https://github.com/urbanjost/M_time.git" }
M_system    = { git = "https://github.com/urbanjost/M_system.git" }
M_messages    = { git = "https://github.com/urbanjost/M_messages.git" }
M_kracken = { git = "https://github.com/urbanjost/M_kracken.git" }
